/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as AuthenticatedAppMailRouteImport } from './routes/_authenticated/_app/mail'
import { Route as AuthenticatedAppComposeRouteImport } from './routes/_authenticated/_app/compose'
import { Route as AuthenticatedAppSettingsIndexRouteImport } from './routes/_authenticated/_app/settings/index'
import { Route as AuthenticatedAppMailIndexRouteImport } from './routes/_authenticated/_app/mail/index'
import { Route as AuthenticatedAppSettingsAccountRouteImport } from './routes/_authenticated/_app/settings/account'
import { Route as AuthenticatedAppMailMailboxRouteImport } from './routes/_authenticated/_app/mail/$mailbox'
import { Route as AuthenticatedAppSettingsLabelIndexRouteImport } from './routes/_authenticated/_app/settings/label/index'
import { Route as AuthenticatedAppSettingsLabelLabelIdRouteImport } from './routes/_authenticated/_app/settings/label/$labelId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMailRoute = AuthenticatedAppMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppComposeRoute = AuthenticatedAppComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppMailIndexRoute =
  AuthenticatedAppMailIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppMailRoute,
  } as any)
const AuthenticatedAppSettingsAccountRoute =
  AuthenticatedAppSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppMailMailboxRoute =
  AuthenticatedAppMailMailboxRouteImport.update({
    id: '/$mailbox',
    path: '/$mailbox',
    getParentRoute: () => AuthenticatedAppMailRoute,
  } as any)
const AuthenticatedAppSettingsLabelIndexRoute =
  AuthenticatedAppSettingsLabelIndexRouteImport.update({
    id: '/label/',
    path: '/label/',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsLabelLabelIdRoute =
  AuthenticatedAppSettingsLabelLabelIdRouteImport.update({
    id: '/label/$labelId',
    path: '/label/$labelId',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/compose': typeof AuthenticatedAppComposeRoute
  '/mail': typeof AuthenticatedAppMailRouteWithChildren
  '/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/mail/$mailbox': typeof AuthenticatedAppMailMailboxRoute
  '/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/mail/': typeof AuthenticatedAppMailIndexRoute
  '/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/settings/label/$labelId': typeof AuthenticatedAppSettingsLabelLabelIdRoute
  '/settings/label/': typeof AuthenticatedAppSettingsLabelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/compose': typeof AuthenticatedAppComposeRoute
  '/mail/$mailbox': typeof AuthenticatedAppMailMailboxRoute
  '/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/mail': typeof AuthenticatedAppMailIndexRoute
  '/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/settings/label/$labelId': typeof AuthenticatedAppSettingsLabelLabelIdRoute
  '/settings/label': typeof AuthenticatedAppSettingsLabelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_authenticated/_app/compose': typeof AuthenticatedAppComposeRoute
  '/_authenticated/_app/mail': typeof AuthenticatedAppMailRouteWithChildren
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/_authenticated/_app/mail/$mailbox': typeof AuthenticatedAppMailMailboxRoute
  '/_authenticated/_app/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/_authenticated/_app/mail/': typeof AuthenticatedAppMailIndexRoute
  '/_authenticated/_app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/_authenticated/_app/settings/label/$labelId': typeof AuthenticatedAppSettingsLabelLabelIdRoute
  '/_authenticated/_app/settings/label/': typeof AuthenticatedAppSettingsLabelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/privacy'
    | '/terms'
    | '/upgrade'
    | '/login'
    | '/signup'
    | '/compose'
    | '/mail'
    | '/settings'
    | '/mail/$mailbox'
    | '/settings/account'
    | '/mail/'
    | '/settings/'
    | '/settings/label/$labelId'
    | '/settings/label/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/privacy'
    | '/terms'
    | '/upgrade'
    | '/login'
    | '/signup'
    | '/compose'
    | '/mail/$mailbox'
    | '/settings/account'
    | '/mail'
    | '/settings'
    | '/settings/label/$labelId'
    | '/settings/label'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_authenticated'
    | '/_guest'
    | '/privacy'
    | '/terms'
    | '/_authenticated/_app'
    | '/_authenticated/upgrade'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_authenticated/_app/compose'
    | '/_authenticated/_app/mail'
    | '/_authenticated/_app/settings'
    | '/_authenticated/_app/mail/$mailbox'
    | '/_authenticated/_app/settings/account'
    | '/_authenticated/_app/mail/'
    | '/_authenticated/_app/settings/'
    | '/_authenticated/_app/settings/label/$labelId'
    | '/_authenticated/_app/settings/label/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/mail': {
      id: '/_authenticated/_app/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof AuthenticatedAppMailRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/compose': {
      id: '/_authenticated/_app/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AuthenticatedAppComposeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/': {
      id: '/_authenticated/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/_app/mail/': {
      id: '/_authenticated/_app/mail/'
      path: '/'
      fullPath: '/mail/'
      preLoaderRoute: typeof AuthenticatedAppMailIndexRouteImport
      parentRoute: typeof AuthenticatedAppMailRoute
    }
    '/_authenticated/_app/settings/account': {
      id: '/_authenticated/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedAppSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/_app/mail/$mailbox': {
      id: '/_authenticated/_app/mail/$mailbox'
      path: '/$mailbox'
      fullPath: '/mail/$mailbox'
      preLoaderRoute: typeof AuthenticatedAppMailMailboxRouteImport
      parentRoute: typeof AuthenticatedAppMailRoute
    }
    '/_authenticated/_app/settings/label/': {
      id: '/_authenticated/_app/settings/label/'
      path: '/label'
      fullPath: '/settings/label/'
      preLoaderRoute: typeof AuthenticatedAppSettingsLabelIndexRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/_app/settings/label/$labelId': {
      id: '/_authenticated/_app/settings/label/$labelId'
      path: '/label/$labelId'
      fullPath: '/settings/label/$labelId'
      preLoaderRoute: typeof AuthenticatedAppSettingsLabelLabelIdRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
  }
}

interface AuthenticatedAppMailRouteChildren {
  AuthenticatedAppMailMailboxRoute: typeof AuthenticatedAppMailMailboxRoute
  AuthenticatedAppMailIndexRoute: typeof AuthenticatedAppMailIndexRoute
}

const AuthenticatedAppMailRouteChildren: AuthenticatedAppMailRouteChildren = {
  AuthenticatedAppMailMailboxRoute: AuthenticatedAppMailMailboxRoute,
  AuthenticatedAppMailIndexRoute: AuthenticatedAppMailIndexRoute,
}

const AuthenticatedAppMailRouteWithChildren =
  AuthenticatedAppMailRoute._addFileChildren(AuthenticatedAppMailRouteChildren)

interface AuthenticatedAppSettingsRouteChildren {
  AuthenticatedAppSettingsAccountRoute: typeof AuthenticatedAppSettingsAccountRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
  AuthenticatedAppSettingsLabelLabelIdRoute: typeof AuthenticatedAppSettingsLabelLabelIdRoute
  AuthenticatedAppSettingsLabelIndexRoute: typeof AuthenticatedAppSettingsLabelIndexRoute
}

const AuthenticatedAppSettingsRouteChildren: AuthenticatedAppSettingsRouteChildren =
  {
    AuthenticatedAppSettingsAccountRoute: AuthenticatedAppSettingsAccountRoute,
    AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
    AuthenticatedAppSettingsLabelLabelIdRoute:
      AuthenticatedAppSettingsLabelLabelIdRoute,
    AuthenticatedAppSettingsLabelIndexRoute:
      AuthenticatedAppSettingsLabelIndexRoute,
  }

const AuthenticatedAppSettingsRouteWithChildren =
  AuthenticatedAppSettingsRoute._addFileChildren(
    AuthenticatedAppSettingsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppComposeRoute: typeof AuthenticatedAppComposeRoute
  AuthenticatedAppMailRoute: typeof AuthenticatedAppMailRouteWithChildren
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRouteWithChildren
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppComposeRoute: AuthenticatedAppComposeRoute,
  AuthenticatedAppMailRoute: AuthenticatedAppMailRouteWithChildren,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRouteWithChildren,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
