/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMailRouteImport } from './routes/_authenticated/mail'
import { Route as AuthenticatedComposeRouteImport } from './routes/_authenticated/compose'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedMailIndexRouteImport } from './routes/_authenticated/mail/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedMailMailboxRouteImport } from './routes/_authenticated/mail/$mailbox'
import { Route as AuthenticatedSettingsLabelIndexRouteImport } from './routes/_authenticated/settings/label/index'
import { Route as AuthenticatedSettingsLabelLabelIdRouteImport } from './routes/_authenticated/settings/label/$labelId'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMailRoute = AuthenticatedMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComposeRoute = AuthenticatedComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedMailIndexRoute = AuthenticatedMailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMailRoute,
} as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedMailMailboxRoute =
  AuthenticatedMailMailboxRouteImport.update({
    id: '/$mailbox',
    path: '/$mailbox',
    getParentRoute: () => AuthenticatedMailRoute,
  } as any)
const AuthenticatedSettingsLabelIndexRoute =
  AuthenticatedSettingsLabelIndexRouteImport.update({
    id: '/label/',
    path: '/label/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLabelLabelIdRoute =
  AuthenticatedSettingsLabelLabelIdRouteImport.update({
    id: '/label/$labelId',
    path: '/label/$labelId',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/mail': typeof AuthenticatedMailRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/mail/$mailbox': typeof AuthenticatedMailMailboxRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/mail/': typeof AuthenticatedMailIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/settings/label/$labelId': typeof AuthenticatedSettingsLabelLabelIdRoute
  '/settings/label/': typeof AuthenticatedSettingsLabelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/mail/$mailbox': typeof AuthenticatedMailMailboxRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/mail': typeof AuthenticatedMailIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/label/$labelId': typeof AuthenticatedSettingsLabelLabelIdRoute
  '/settings/label': typeof AuthenticatedSettingsLabelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_authenticated/compose': typeof AuthenticatedComposeRoute
  '/_authenticated/mail': typeof AuthenticatedMailRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_authenticated/mail/$mailbox': typeof AuthenticatedMailMailboxRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/mail/': typeof AuthenticatedMailIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/label/$labelId': typeof AuthenticatedSettingsLabelLabelIdRoute
  '/_authenticated/settings/label/': typeof AuthenticatedSettingsLabelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compose'
    | '/mail'
    | '/settings'
    | '/login'
    | '/signup'
    | '/mail/$mailbox'
    | '/settings/account'
    | '/mail/'
    | '/settings/'
    | '/settings/label/$labelId'
    | '/settings/label/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compose'
    | '/login'
    | '/signup'
    | '/mail/$mailbox'
    | '/settings/account'
    | '/mail'
    | '/settings'
    | '/settings/label/$labelId'
    | '/settings/label'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_guest'
    | '/_authenticated/compose'
    | '/_authenticated/mail'
    | '/_authenticated/settings'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_authenticated/mail/$mailbox'
    | '/_authenticated/settings/account'
    | '/_authenticated/mail/'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/label/$labelId'
    | '/_authenticated/settings/label/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mail': {
      id: '/_authenticated/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof AuthenticatedMailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compose': {
      id: '/_authenticated/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AuthenticatedComposeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/mail/': {
      id: '/_authenticated/mail/'
      path: '/'
      fullPath: '/mail/'
      preLoaderRoute: typeof AuthenticatedMailIndexRouteImport
      parentRoute: typeof AuthenticatedMailRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/mail/$mailbox': {
      id: '/_authenticated/mail/$mailbox'
      path: '/$mailbox'
      fullPath: '/mail/$mailbox'
      preLoaderRoute: typeof AuthenticatedMailMailboxRouteImport
      parentRoute: typeof AuthenticatedMailRoute
    }
    '/_authenticated/settings/label/': {
      id: '/_authenticated/settings/label/'
      path: '/label'
      fullPath: '/settings/label/'
      preLoaderRoute: typeof AuthenticatedSettingsLabelIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/label/$labelId': {
      id: '/_authenticated/settings/label/$labelId'
      path: '/label/$labelId'
      fullPath: '/settings/label/$labelId'
      preLoaderRoute: typeof AuthenticatedSettingsLabelLabelIdRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
  }
}

interface AuthenticatedMailRouteChildren {
  AuthenticatedMailMailboxRoute: typeof AuthenticatedMailMailboxRoute
  AuthenticatedMailIndexRoute: typeof AuthenticatedMailIndexRoute
}

const AuthenticatedMailRouteChildren: AuthenticatedMailRouteChildren = {
  AuthenticatedMailMailboxRoute: AuthenticatedMailMailboxRoute,
  AuthenticatedMailIndexRoute: AuthenticatedMailIndexRoute,
}

const AuthenticatedMailRouteWithChildren =
  AuthenticatedMailRoute._addFileChildren(AuthenticatedMailRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsLabelLabelIdRoute: typeof AuthenticatedSettingsLabelLabelIdRoute
  AuthenticatedSettingsLabelIndexRoute: typeof AuthenticatedSettingsLabelIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsLabelLabelIdRoute:
    AuthenticatedSettingsLabelLabelIdRoute,
  AuthenticatedSettingsLabelIndexRoute: AuthenticatedSettingsLabelIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedComposeRoute: typeof AuthenticatedComposeRoute
  AuthenticatedMailRoute: typeof AuthenticatedMailRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedComposeRoute: AuthenticatedComposeRoute,
  AuthenticatedMailRoute: AuthenticatedMailRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
